// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ITp7CkKfg-JEZX61Xvu0L3TeCy8fKJo',
    appId: '1:596185850951:web:6b46fe0914d2732edb7d62',
    messagingSenderId: '596185850951',
    projectId: 'blogapp-53499',
    authDomain: 'blogapp-53499.firebaseapp.com',
    storageBucket: 'blogapp-53499.appspot.com',
    measurementId: 'G-RJ9M1K7X5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcLW7Pwa94g5zWiwdVoVyvAfXQLeaDhK4',
    appId: '1:596185850951:android:45159ce673922854db7d62',
    messagingSenderId: '596185850951',
    projectId: 'blogapp-53499',
    storageBucket: 'blogapp-53499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZf6PPwAWavXIdFJE1CBof4Vo87x2U2o',
    appId: '1:596185850951:ios:660bb31d87ec320bdb7d62',
    messagingSenderId: '596185850951',
    projectId: 'blogapp-53499',
    storageBucket: 'blogapp-53499.appspot.com',
    iosBundleId: 'com.example.finalBlogProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZf6PPwAWavXIdFJE1CBof4Vo87x2U2o',
    appId: '1:596185850951:ios:7ec38f8ac84e8443db7d62',
    messagingSenderId: '596185850951',
    projectId: 'blogapp-53499',
    storageBucket: 'blogapp-53499.appspot.com',
    iosBundleId: 'com.example.finalBlogProject.RunnerTests',
  );
}
